### ISSUE TITLE
Suggestion to add a method to return default value provided by user if Val is not Valid

### ISSUE THREAD

**Issue by apatniv** [LukaGiorgadze/gonull#14]
Thanks for providing a useful library. 

Currently, I need to do the following to determine the default value 

```
const defaultPath = "magic.dat" // somewhere in the package

optPath := gonull.NewNullable("hello.dat")
path := ""
if optPath.Valid {
    path = optPath.Val
} else {
    path = defaultPath
}
```

Suggestion is to add a new receiver method `OrElse` so that this can be done in one line 

```
path := optPath.OrElse(defaultPath)
```

Signature:

```
func (n *Nullable[T]) OrElse(value T) T
```

**Comment by apatniv** [comment]
I can make the PR if you are ok. Thanks

**Comment by LukaGiorgadze** [comment]
Hey @apatniv, this is really nice feature and I would love to see it in the next release. using `OrElse` we can reduce the amount of if else conditions.

Feel free to rise a PR, I'll be more than happy to approve it.

Thank you for your feedback and open-source contribution.

**Comment by LukaGiorgadze** [comment]
PR #17
